package com.reverseengineering.mapper;

import com.reverseengineering.entity.TbReverse;
import com.reverseengineering.entity.TbReverseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbReverseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    long countByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int deleteByExample(TbReverseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int deleteByPrimaryKey(Integer reId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int insert(TbReverse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int insertSelective(TbReverse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    List<TbReverse> selectByExample(TbReverseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    TbReverse selectByPrimaryKey(Integer reId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbReverse record, @Param("example") TbReverseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int updateByExample(@Param("record") TbReverse record, @Param("example") TbReverseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int updateByPrimaryKeySelective(TbReverse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reverse
     *
     * @mbg.generated Sat Apr 25 23:05:03 CST 2020
     */
    int updateByPrimaryKey(TbReverse record);
}